### ISSUE TITLE
Initial load in iframe scrolls page

### ISSUE THREAD

**Issue by alexandersimoes** [anvaka/yasiv-youtube#1]
On first pageload where I have an embedded iframe the page automatically scrolls to where the iframe is. I couldn't find anything in the source but maybe this is caused by some onpageload event handler on the window that is then propagating up to the parent when it's embedded in an iframe?

**Comment by anvaka** [comment]
This was caused by `autofocus` attribute on the search field. 

I updated code, so that when rendered inside an iframe the autofocus is not set by default. Please check now - it shouldn't scroll page.

**Comment by alexandersimoes** [comment]
Yes that fixed it thx! 🍻
